name: location_manager
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter:
    git:
      url: git://github.com/giancarlopro/plugins.git
      path: packages/google_maps_flutter
      ref: development
  location: ^3.0.2
  permission_handler: ^5.0.0+hotfix.8
  location_permissions: ^3.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
